/* Divs 20 Rectangles
*/
//
println(displayWidth, displayHeight);
fullScreen();
int appWidth = displayWidth;
int appHeight = displayHeight;
//
int paperWidth = 280;
int paperHeight = 210;
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 

//rect( SongTitleDivX, SongTitleDivY, SongTitleDivWidth, SongTitleDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight;
//rect( PlayButtonDivX, PlayButtonDivY, PlayButtonDivWidth, PlayButtonDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( PauseButtonDivX, PauseButtonDivY, PauseButtonDivWidth, PauseButtonDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( SkipTenDivX, SkipTenDivY, SkipTenDivWidth, SkipTenDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( BackTenDivX, BackTenDivY, BackTenDivWidth, BackTenDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( SkipSongDivX, SkipSongDivY, SkipSongDivWidth, SkipSongDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( PrevSongDivX, PrevSongDivY, PrevSongDivWidth, PrevSongDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( UnmuteDivX, UnmuteDivY, UnmuteDivWidth, UnmuteDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( MuteDivX, MuteDivY, MuteDivWidth, MuteDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( ShuffleDivX,  ShuffleDivY,  ShuffleDivWidth,  ShuffleDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( NoScreenDivX, NoScreenDivY, NoScreenDivWidth, NoScreenDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( DoubleSpeedDivX, DoubleSpeedDivY, DoubleSpeedDivWidth, DoubleSpeedDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( PlaylistDivX, PlaylistDivY, PlaylistDivWidth, PlaylistDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( ExitButtonDivX, ExitButtonDivY, ExitButtonDivWidth, ExitButtonDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( ScreenDivX, ScreenDivY, ScreenDivWidth, ScreenDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
//rect( SongBarDivX, SongBarDivY, SongBarDivWidth, SongBarDivHeight );
float DivX = appWidth * ??? / paperWidth; 
float DivY = appHeight * ??? / paperHeight; 
float DivWidth = appWidth * ??? / paperWidth;  
float DivHeight = appHeight * ??? / paperHeight; 
